<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>magnet_description</name>
  <version>0.0.1</version>
  <description>Description for Magnet mapping device</description>
  <maintainer email="tobit@robots.ox.ac.uk">Tobit Flatscher</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>hesai_description</depend>
  <depend>microstrain_inertial_description</depend>
  <depend>rviz</depend>
  <depend>xacro</depend>
</package>